# Generated by Django 3.2.12 on 2023-12-16 06:06

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media/ads/'),
        ),
    ]
